export default {
    name: 'shadcn',
    description: 'A set of beautifully designed components that you can customize, extend, and build on. Start here then make it your own. Open Source. Open Code.',
    url: 'https://ui.shadcn.com',
    registry: {
        components: [
            "accordion",
            "alert",
            "alert-dialog",
            "aspect-ratio",
            "avatar",
            "badge",
            "breadcrumb",
            "button",
            "calendar",
            "card",
            "carousel",
            "chart",
            "checkbox",
            "collapsible",
            "combobox",
            "command",
            "context-menu",
            "data-table",
            "date-picker",
            "dialog",
            "drawer",
            "dropdown-menu",
            "react-hook-form",
            "hover-card",
            "input",
            "input-otp",
            "label",
            "menubar",
            "navigation-menu",
            "pagination",
            "popover",
            "progress",
            "radio-group",
            "resizable",
            "scroll-area",
            "select",
            "separator",
            "sheet",
            "sidebar",
            "skeleton",
            "slider",
            "sonner",
            "switch",
            "table",
            "tabs",
            "textarea",
            "toast",
            "toggle",
            "toggle-group",
            "tooltip",
            "typography"
        ]
    },
}